import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {

  return (
    <Html lang="is">
      <Head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicons/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicons/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicons/site.webmanifest" />
        <link
          rel="mask-icon"
          href="/favicons/safari-pinned-tab.svg"
          color="#3076da"
        />
        <meta name="msapplication-TileColor" content="#3076da" />
        <meta name="theme-color" content="#3076da" />
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://styles.reykjavik.is/bundle/v0.8?m=-basics,AccordionList,ActionCards,Attention,BreadCrumbs,ButtonPrimary,ButtonSecondary,ButtonTertiary,ButtonBack,CityBlock,ExtraLinks,Form,WizardStepper,WizardLayout,WizardLayoutClose,TextInput,Checkbox,CheckboxGroup,CheckboxButtonsGroup,CheckboxButton,GridBlocks,HeroBlock,Modal,TextBlock,Datepicker,Tabs,FooterInfo,Layout-full,Heading,SubHeading,PageHeading,MainMenu,Selectbox,TagPill,NameCards,FileInput,InfoBlock,IslandPageBlock,SearchInput,PageFilter,RadioButtonsGroup"
        />
      </Head>
      <body className={'bgrBubbles'}>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
