<<<<<<< HEAD
import Head from "next/head";
// import styles from "../styles/Home.module.css";
=======
import Head from "next/head"
>>>>>>> 402c62d (Add _documents.js file and update layout. Add form and form component files.)
import { useSession, signIn, signOut } from "next-auth/react"


export default function Home() {
  const { data: session } = useSession()
  if(session) {
    return <>
      Signed in as {session.user.email} <br/>
      <button onClick={() => signOut()}>Sign out</button>
    </>
  }

  return (
<<<<<<< HEAD
    <>
      <Head>
        <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png" />
        <link rel="manifest" href="/favicons/site.webmanifest" />
        <link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#3076da" />
        <meta name="msapplication-TileColor" content="#3076da" />
        <meta name="theme-color" content="#3076da" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://styles.reykjavik.is/bundle/v0.8?m=-basics,Layout,MainMenu,FooterInfo"
        />
      </Head>

    </>
=======
    <div className="container">
      <Head>
        <title>Home Page</title>
      </Head>

    </div>
>>>>>>> 402c62d (Add _documents.js file and update layout. Add form and form component files.)
  );
}
