import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Application from "./pageComponents/Application";
import Head from 'next/head'
import { useSession, signIn, signOut } from "next-auth/react"

export default function Home() {
  const { data: session } = useSession()
  if(session) {
    return <>
      Signed in as {session.user.email} <br/>
      <button onClick={() => signOut()}>Sign out</button>
    </>
  }

  return (
    <div className={styles.container}>
      <link
        rel="stylesheet"
        type="text/css"
        href="https://styles.reykjavik.is/bundle/v0.8?m=-basics,AccordionList,ActionCards,Attention,BreadCrumbs,ButtonPrimary,ButtonSecondary,ButtonTertiary,ButtonBack,CityBlock,ExtraLinks,Form,WizardStepper,WizardLayout,WizardLayoutClose,TextInput,Checkbox,CheckboxGroup,CheckboxButtonsGroup,CheckboxButton,GridBlocks,HeroBlock,Modal,TextBlock,Datepicker,Tabs,FooterInfo,Layout-full,Heading,SubHeading,PageHeading,MainMenu,Selectbox,TagPill,NameCards,FileInput,InfoBlock,IslandPageBlock,SearchInput,PageFilter,RadioButtonsGroup"
      ></link>
      <Head>
        <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png" />
        <link rel="manifest" href="/favicons/site.webmanifest" />
        <link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#3076da" />
        <meta name="msapplication-TileColor" content="#3076da" />
        <meta name="theme-color" content="#3076da" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Application />
        <h1>Not signed in</h1>
        <button onClick={() => signIn()}>Sign in</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
