import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Application from "./pageComponents/Application";

export default function Home() {
  return (
    <div className={styles.container}>
      <link
        rel="stylesheet"
        type="text/css"
        href="https://styles.reykjavik.is/bundle/v0.8?m=-basics,AccordionList,ActionCards,Attention,BreadCrumbs,ButtonPrimary,ButtonSecondary,ButtonTertiary,ButtonBack,CityBlock,ExtraLinks,Form,WizardStepper,WizardLayout,WizardLayoutClose,TextInput,Checkbox,CheckboxGroup,CheckboxButtonsGroup,CheckboxButton,GridBlocks,HeroBlock,Modal,TextBlock,Datepicker,Tabs,FooterInfo,Layout-full,Heading,SubHeading,PageHeading,MainMenu,Selectbox,TagPill,NameCards,FileInput,InfoBlock,IslandPageBlock,SearchInput,PageFilter,RadioButtonsGroup"
      ></link>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Application />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
